### ISSUE TITLE
Pin xarray to a compatible version.

### ISSUE THREAD

**Issue by sharkinsspatial** [pangeo-forge/pangeo-forge#111]
Since https://github.com/pydata/xarray/pull/5065/ has been merged it would be helpful to pin xarray to the Github `master` branch in `requirements.txt` in the interim until the `safe_chunks` functionality is in release.  Currently installing `pangeo_forge` in the image for our Dask workers requires special install ordering to avoid `pangeo-forge` potentially using a cached xarray version.

**Comment by rabernat** [comment]
> would be helpful to pin xarray to the Github `master` branch in `requirements.txt`

Definitely! Could you make a PR?

**Comment by rabernat** [comment]
Let me know if you need any advice on how to make the PR for this.
