### ISSUE TITLE
Source URL pattern

### ISSUE THREAD

**Issue by davidbrochart** [pangeo-forge/pangeo-forge#2]
I was wondering how we can handle a URL like this one (from the GPM IMERG dataset):
```
ftp://jsimpson.pps.eosdis.nasa.gov/NRTPUB/imerg/late/200006/3B-HHR-L.MS.MRG.3IMERG.20000601-S000000-E002959.0000.V06B.RT-H5
```
It doesn't just specify a date-time, but also a time range (from `00:00:00` to `00:29:59`).

There is also a number of minutes since the beginning of the day, like `0270` in the following URL:
```
ftp://jsimpson.pps.eosdis.nasa.gov/NRTPUB/imerg/late/200006/3B-HHR-L.MS.MRG.3IMERG.20000601-S043000-E045959.0270.V06B.RT-H5
```

**Comment by rabernat** [comment]
In the new iteration of recipes, the user has to provide an explicit list of input urls. So I'm closing this for now.
