### ISSUE TITLE
Handle inputs with variable items per input

### ISSUE THREAD

**Issue by rabernat** [pangeo-forge/pangeo-forge#50]
This problem was originally noted by @naomi-henderson in #47.

Our current recipe assumes that the number of "items" per input is constant:

https://github.com/pangeo-forge/pangeo-forge/blob/f9b698a35a62ab169bce546b15fef9722c70cd90/pangeo_forge/recipe.py#L149

where "items" refers to the length along the `sequence_dim` dimension (e.g. time). This assumptions buys us something big: we don't have to examine each input file, and we can determine which region of the target to write each chunk to using simple math:

https://github.com/pangeo-forge/pangeo-forge/blob/f9b698a35a62ab169bce546b15fef9722c70cd90/pangeo_forge/recipe.py#L304-L310

This makes sense for 1-file-per-day netCDFs, but many datasets have variable sizes, e.g. one file per month (31 days, 30, days, 28 days) or just whatever random stuff CMIP models do. For those cases, we will inevitably have to peek into each input file to determine its dimensions / shape and pass this information on to `prepare_target` and `store_chunk` somehow.

Here are some of the issues raised by this scenario

### How to determine the total size of the target dataset?

In the current recipe class, we calculate the length along `sequence_dim` deterministically as 

https://github.com/pangeo-forge/pangeo-forge/blob/f9b698a35a62ab169bce546b15fef9722c70cd90/pangeo_forge/recipe.py#L312-L314

and then use it to resize the target zarr.

https://github.com/pangeo-forge/pangeo-forge/blob/f9b698a35a62ab169bce546b15fef9722c70cd90/pangeo_forge/recipe.py#L183

A key point is that the size of the dataset is known from the beginning, without reading any files.

For these uneven datasets, we can't do that. We need to look at each file. Fortunately, we already almost do that, when we cache the inputs.

**I propose we write a .json "sidecar" file for each input that contains the dataset shape, variables, etc.**. A very easy way to do this would using xarray's [to_dict](http://xarray.pydata.org/en/stable/generated/xarray.DataArray.to_dict.html) function (with `data=False`) from `cache_input`. Reading these files should be cheap enough that we can read them all in `prepare_target`. Then we can figure out how big the target dataset will be.

### How to handle chunking and chunk overlap?

Currently we assume a fixed number of `inputs_per_chunk`, which implies the pangeo forge "chunks" will vary in size and not line up with the target chunks (zarr chunks have to be constant shape). Our whole lexicon breaks down a bit, since pangeo-forge's "chunks" no longer map directly to target zarr chunks. We possibly need a new parameter, `target_chunks`, to specify the target chunking explicitly.

I see two different directions we could go to handle the problem of overlap:
- Keep `inputs_per_chunk` fixed, accept that pangeo-forge chunks will not line up with zarr chunks, and either
  - switch to append-style writes (as in the original recipe). We lose the ability for concurrency in the `store_chunk` stage, as the appends have to be sequential.
  - manually calculate the overlap between the pangeo-forge chunks (irregular) and the zarr chunks (regular). Then use distributed locks (also raised in #45) to prevent concurrent writes to a the same zarr chunk by different processes in `store_chunk`. 
- Keep the 1:1 mapping between between pangeo-forge chunks and zarr chunks, but break the requirement that `inputs_per_chunk` be fixed. Instead, allow multiple different chunks to draw from the same input. `open_chunk` possibly needs to figure out how to subset inputs. This is maybe easier because we don't need locks for concurrent reads. However, _it makes it impossible to precalculate the number of `store_chunk` tasks_, since we don't know the total size of the dataset until we start running the recipe! 🤯 This would violate our current Pipeline execution model and require a deeper refactoring of execution.

In any case, the `open_chunk` and `store_chunk` functions will need to have more context about the dataset they are writing to and their position within it. This information could possibly be calculated and stored with the sidecar file mentioned above.

---

In general, I think we should not hesitate to use the storage layer to communicate. The alternative is having tasks pass information to each other directly within the pipeline. Currently all of the pipeline function calls and arguments are determined at the outset, when the recipe is initialized, and none of the functions return anything. Changing that would be a pretty deep change at this point and would likely force us to drop this whole Pipeline structure I've cooked up and just start writing prefect task / flows directly again.

**Comment by rabernat** [comment]
This connects somewhat to #49 as well (multiple chunks per input). In both cases, there is going to be a more complex relationship between inputs and chunks.

**Comment by swnesbitt** [comment]
I am hitting this issue when accumulating over a `sequence_dim` that changes from file to file.  This is satellite data with a variable number of data points per orbit.

```python
ValueError: variable 'Latitude' already exists with different dimension sizes: {'pixel': 20} != {'pixel': 373721}. to_zarr() only supports changing dimension sizes when explicitly appending, but append_dim=None.
```

It is interesting that I can see the `xarray` chunks just fine, but when I go to write the chunks to `zarr` it fails.

I tried modifying the `zarr` write to include the `self.sequence_dim` in the write and append, but then it complained that appending and region are incompatible (which makes sense).

Not quite sure how to proceed - thinking that a rechunk is probably necessary when writing in these cases?

**Comment by rabernat** [comment]
Hi @swnesbitt -- thanks for your comment! TBH, I had no idea that anyone was using pangeo-forge "in the wild"! 😆  I'm not surprised you hit some errors, as pangeo-forge is still very raw and rough.

We have some ideas about how to fix the specific issue I described above. To understand if this is related to your problem, we would need a bit more detail from you. Could you post your full recipe code and share the details of the input files (e.g. output from `ncdump`)?

**Comment by swnesbitt** [comment]
Thanks! Yes, the recipe is here: [https://gist.github.com/swnesbitt/0f506fbfea004eb8c1bd721d69a525bb](https://gist.github.com/swnesbitt/0f506fbfea004eb8c1bd721d69a525bb).

Below is the ncdump output for one of the files. I am trying to concatenate the zarr along dim `pixel`:

```
(base) snesbitt@keeling-g18 /data/accp/a/snesbitt/reduced-trmm/1998/01$ ncdump -h L2RADAR_v4.19980131-S185411-E202529.001024.V06A.HDF5.nc
netcdf L2RADAR_v4.19980131-S185411-E202529.001024.V06A.HDF5 {
dimensions:
        pixel = 21761 ;
        range = 176 ;
        dim2 = 2 ;
        ray = 9139 ;
        scan = 49 ;
        dim3 = 3 ;
variables:
        float Latitude(pixel) ;
                Latitude:_FillValue = NaNf ;
        float Longitude(pixel) ;
                Longitude:_FillValue = NaNf ;
        short binBBBottom(pixel) ;
        short binBBTop(pixel) ;
        short binRealSurface(pixel) ;
        int64 dim2(dim2) ;
        int64 dim3(dim3) ;
        int flagPrecipKu(ray, scan) ;
        int64 indices_0(pixel) ;
        int64 indices_1(pixel) ;
        int landSurfaceType(pixel) ;
        int orbit(pixel) ;
        float paramDSD(pixel, range, dim2) ;
                paramDSD:_FillValue = NaNf ;
        float piaFinal(pixel) ;
                piaFinal:_FillValue = NaNf ;
        int64 pixel(pixel) ;
        short precipRate(pixel, range) ;
                precipRate:_FillValue = -9999s ;
                precipRate:scale_factor = 0.01 ;
        int64 range(range) ;
        int64 ray(ray) ;
        int64 scan(scan) ;
        double timeMidScan(pixel) ;
                timeMidScan:_FillValue = NaN ;
        int typePrecip(pixel) ;
        short zFactorCorrected(pixel, range) ;
                zFactorCorrected:_FillValue = -9999s ;
                zFactorCorrected:scale_factor = 0.01 ;
        float zFactorCorrectedNearSurface(pixel) ;
                zFactorCorrectedNearSurface:_FillValue = NaNf ;
        short zFactorMeasured(pixel, range) ;
                zFactorMeasured:_FillValue = -9999s ;
                zFactorMeasured:scale_factor = 0.01 ;
}
```

**Comment by rabernat** [comment]
For reference, the recipe creation is here

```python
recipe = NetCDFtoZarrSequentialRecipe(
    input_urls=input_urls,
    sequence_dim="pixel",
    inputs_per_chunk=20,
    xarray_open_kwargs={'drop_variables':['flagPrecipKu']},   
)
```

I notice you are not specifying the `nitems_per_input` parameter. It's default is 1. If all files were the same as this example one, you would use `nitems_per_input=21761`. However, I think that this varies from file to file. This is the core problem.

We plan to support this soon, i.e. within weeks.

Thanks for the useful example. Are these data public? If so, could you open an issue here - https://github.com/pangeo-forge/staged-recipes/issues - to keep track of this potential use case?

**Comment by swnesbitt** [comment]
Yes, it is public NASA level 2 data.  I will certainly post a recipe once I get it working.  Cheers!
