### ISSUE TITLE
Zarr consolidated metadata not working

### ISSUE THREAD

**Issue by rabernat** [pangeo-forge/pangeo-forge#60]
As reported in #51 

> I have also noticed that, despite an indication to the contrary when printing out the recipe:

`NetCDFtoZarrSequentialRecipe(sequence_dim='time', inputs_per_chunk=1, nitems_per_input=600, target=FSSpecTarget(fs=<fsspec.implementations.local.LocalFileSystem object at 0x7f17aa446a50>, root_path='/tmp/tmp37ghyji0'), input_cache=CacheFSSpecTarget(fs=<fsspec.implementations.local.LocalFileSystem object at 0x7f17aa446a50>, root_path='/tmp/tmpvna52uxv'), require_cache=True, consolidate_zarr=True, xarray_open_kwargs={'use_cftime': True}, xarray_concat_kwargs={}, delete_input_encoding=True)`

> there is no .zmetadata being saved - otherwize the zarr store looks fine.

**Comment by rabernat** [comment]
The relevant code is here

https://github.com/pangeo-forge/pangeo-forge/blob/491b04c6135970f551444e041ff2cd85a3dcbe39/pangeo_forge/recipe.py#L216-L223

**Comment by naomi-henderson** [comment]
@rabernat, Oops, I found the problem.  I never called `recipe.finalize_target()`!  But, thanks to your prodding and 'good first issue' label, I found it while trying to actually find and fix the problem myself.  I am slowing getting there ... thanks for your patience ... maybe next time.
