### ISSUE TITLE
Rename this package?

### ISSUE THREAD

**Issue by rabernat** [pangeo-forge/pangeo-forge#75]
Today's discussion / whiteboarding was very useful. It surfaced another point of confusion about naming.

We are currently using the term "Pangeo Forge" for two distinct things
- The overall project
- The `pangeo_forge` python library

Is this confusing? We have not actually released the package yet, so it's really not too late to rename it. Is `pangeo_forge` actually `pangeo_smithy`? Or should we break with them and call it `pangeo_recipe`.

**Comment by davidbrochart** [comment]
I think the analogy with conda-forge would be that this package is the equivalent of `conda-build`, right? `conda-smithy` sets up all the CI to build the recipe, and in our case the CI is actually the bakery, which is independent from pangeo-forge (?).
But I'm not sure we "build" a dataset as in building software. Maybe yes, `pangeo-build` would be fine.

**Comment by rabernat** [comment]
Anyone else from @pangeo-forge/dev-team  thoughts on the package renaming? I think renaming this package will help resolve some of the conceptual confusion around the terminology in pangeo forge.

**Comment by martindurant** [comment]
+0.5: I think the current name is indeed confusing, but I'm not sure from the above if we have settled on a new name.

**Comment by rabernat** [comment]
I lean towards something with "recipe" in it, since this package in practice is based entirely around the recipe concept.

**Comment by rabernat** [comment]
At today's meeting today there seemed to be support for `pangeo_forge_recipes`. I would like to rename this repo but I'm a bit nervous about the ramifications. Are there any tools that can help me find everything that has to be renamed (CI, documentation, setup.py, etc)? Has anyone been through the process of renaming a package before? Pinging @jbusecke and @TomNicholas for help...

**Comment by cisaacstern** [comment]
@rabernat, per our conversation this morning, I'll start working on PR for renaming to `pangeo_forge_recipes` today.

**Comment by jbusecke** [comment]
Cmd+Shift+F (in VScode that is) would be my approach. I haven't yet had to rename a package that was anywhere close to being 'fully developed', so unfortunately I don't have too much advice to offer...

**Comment by cisaacstern** [comment]
@jbusecke the repo is small enough that would probably work, though fwiw I am having success with find-and-replace from the command line as follows: `find . -type f -print0 | xargs -0 sed -i '' -e 's/pangeo_forge/pangeo_forge_recipes/g'`, cf. https://superuser.com/questions/428493/how-can-i-do-a-recursive-find-and-replace-from-the-command-line
