### ISSUE TITLE
Caching with fsspec.local_local and simplecache::url

### ISSUE THREAD

**Issue by aaronspring** [pangeo-forge/pangeo-forge#9]
https://github.com/pangeo-forge/pangeo-forge/blob/9872e86f2f7477fb93fd16b3495981d66e7f5e72/examples/oisst-avhrr-v02r01.py#L27-L33

See https://filesystem-spec.readthedocs.io/en/latest/features.html#caching-files-locally

**Comment by rabernat** [comment]
Thanks for this suggestion. The catch here is that we need to cache into gcsfs or s3, not a local filesystem.

**Comment by aaronspring** [comment]
Sorry. Then this probably won’t work. Just came across this and thought this would fix it
